diarios:
  - tag: "lanacion"
    descripcion: "La Nacion"
    twitter: "@LANACION"
    hashtag: "#LaNacion"
    feed_noticias: "https://www.lanacion.com.ar/ln-news.xml"
    categorias:
      - "politica"
      - "economia"
      - "sociedad"
      - "internacional"
      - "deportes"
      - "espectaculos"
      - "cultura"
      - "lifestyle"
      - "buenos-aires"
      - "tecnologia"
      - "salud"
      - "seguridad"
      - "comunidad"
      - "opinion"
      - "moda-y-belleza"
      - "ciencia"
      - "turismo"
      - "propiedades"
      - "autos"

  - tag: "clarin"
    descripcion: "Clarin"
    twitter: "@clarincom"
    hashtag: "#Clarin"
    feed_noticias: "https://www.clarin.com/sitemap_google_news.xml"
    categorias:
      - "politica"
      - "economia"
      - "sociedad"
      - "internacional"
      - "deportes"
      - "espectaculos"
      - "cultura"
      - "policiales"
      - "opinion"
      - "viajes"
      - "rural"
      - "revista-n"
      - "tecnologia"
      - "autos"
      - "ciudades"
      - "entremujeres"
      - "buena-vida"
      - "cartas-al-pais"
      - "arq"
      - "viva"
      - "musica"

  - tag: "infobae"
    descripcion: "Infobae"
    twitter: "@infobae"
    hashtag: "#Infobae"
    feed_noticias: "https://www.infobae.com/feeds/rss/"
    categorias:
      - "politica"
      - "economia"
      - "sociedad"
      - "espectaculos"
      - "cultura"
      - "internacional"
      - "deportes"
      - "tecno"
      - "opinion"
      - "campo"
      - "inhouse"
      - "tendencias"
      - "salud"
      - "gente"

  - tag: "paginadoce"
    descripcion: "Pagina 12"
    twitter: "@pagina12"
    hashtag: "#Pagina12"
    feed_noticias: "https://www.pagina12.com.ar/breakingnews.xml"
    categorias:
      - "politica"
      - "economia"
      - "sociedad"
      - "internacional"
      - "deportes"
      - "espectaculos"
      - "cultura"
      - "universidad"
      - "plastica"
      - "no"
      - "la ventana"
      - "ciencia"
      - "soy"
      - "psicologia"
      - "las12"
      - "radar"
      - "radar libros"
      - "rosario12"

  - tag: "eldestape"
    descripcion: "El Destape"
    twitter: "@eldestapeweb"
    hashtag: "#ElDestape"
    feed_noticias: "https://www.eldestapeweb.com/sitemap-news.xml"
    categorias: 
      - "politica"
      - "economia"
      - "sociedad"
      - "internacional"
      - "deportes"
      - "espectaculos"
      - "cultura"
      - "universidad"
      - "plastica"
      - "no"
      - "la ventana"
      - "ciencia"
      - "soy"
      - "psicologia"
      - "las12"
      - "radar"
      - "radar libros"
      - "rosario12"

  - tag: "telam"
    descripcion: "Telam"
    twitter: "@AgenciaTelam"
    hashtag: "#Telam"
    feeds:
      - tag: "politica"
        url: "https://www.telam.com.ar/rss2/politica.xml"
      - tag: "economia"
        url: "https://www.telam.com.ar/rss2/economia.xml"
      - tag: "sociedad"
        url: "https://www.telam.com.ar/rss2/sociedad.xml"
      - tag: "internacional"
        url: "https://www.telam.com.ar/rss2/internacional.xml"
      - tag: "deportes"
        url: "https://www.telam.com.ar/rss2/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.telam.com.ar/rss2/espectaculos.xml"
      - tag: "cultura"
        url: "https://www.telam.com.ar/rss2/cultura.xml"
      - tag: "policiales"
        url: "https://www.telam.com.ar/rss2/policiales.xml"
      - tag: "latinoamerica"
        url: "https://www.telam.com.ar/rss2/latinoamerica.xml"
      - tag: "conosur"
        url: "https://www.telam.com.ar/rss2/conosur.xml"
      - tag: "provincias"
        url: "https://www.telam.com.ar/rss2/provincias.xml"
      - tag: "agropecuario"
        url: "https://www.telam.com.ar/rss2/agropecuario.xml"
      - tag: "tecnologia"
        url: "https://www.telam.com.ar/rss2/tecnologia.xml"
      - tag: "turismo"
        url: "https://www.telam.com.ar/rss2/turismo.xml"
      - tag: "salud"
        url: "https://www.telam.com.ar/rss2/salud.xml"
      - tag: "educacion"
        url: "https://www.telam.com.ar/rss2/educacion.xml"
      - tag: "redes"
        url: "https://www.telam.com.ar/rss2/redes.xml"

  - tag: "perfil"
    descripcion: "Perfil"
    twitter: "@perfilcom"
    hashtag: "#Perfil"
    feeds:
      - tag: "politica"
        url: "https://www.perfil.com/rss/politica.xml"
      - tag: "economia"
        url: "https://www.perfil.com/rss/economia.xml"
      - tag: "sociedad"
        url: "https://www.perfil.com/rss/sociedad.xml"
      - tag: "internacional"
        url: "https://www.perfil.com/rss/internacional.xml"
      - tag: "deportes"
        url: "https://www.perfil.com/rss/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.perfil.com/rss/espectaculos.xml"
      - tag: "cultura"
        url: "https://www.perfil.com/rss/cultura.xml"
      - tag: "policiales"
        url: "https://www.perfil.com/rss/policia.xml"
      - tag: "opinion"
        url: "https://www.perfil.com/rss/opinion.xml"
      - tag: "ciencia"
        url: "https://www.perfil.com/rss/ciencia.xml"
      - tag: "salud"
        url: "https://www.perfil.com/rss/salud.xml"
      - tag: "tecnologia"
        url: "https://www.perfil.com/rss/tecnologia.xml"

  - tag: "ambito"
    descripcion: "Ambito"
    twitter: "@Ambitocom"
    hashtag: "#AmbitoFinanciero"
    feeds:
      - tag: "politica"
        url: "https://www.ambito.com/rss/politica.xml"
      - tag: "economia"
        url: "https://www.ambito.com/rss/economia.xml"
      - tag: "sociedad"
        url: "https://www.ambito.com/rss/informacion-general.xml"
      - tag: "internacional"
        url: "https://www.ambito.com/rss/mundo.xml"
      - tag: "deportes"
        url: "https://www.ambito.com/rss/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.ambito.com/rss/espectaculos.xml"
      - tag: "finanzas"
        url: "https://www.ambito.com/rss/finanzas.xml"
      - tag: "negocios"
        url: "https://www.ambito.com/rss/negocios.xml"
      - tag: "lifestyle"
        url: "https://www.ambito.com/rss/lifestyle.xml"
      - tag: "estilo-a"
        url: "https://www.ambito.com/rss/estilo-a.xml"
      - tag: "novedades-fiscales"
        url: "https://www.ambito.com/rss/novedades-fiscales.xml"
      - tag: "opinion"
        url: "https://www.ambito.com/rss/opinion.xml"
      - tag: "nacional"
        url: "https://www.ambito.com/rss/nacional.xml"
      - tag: "ambito-biz"
        url: "https://www.ambito.com/rss/ambito-biz.xml"

  - tag: "tn"
    descripcion: "TN"
    twitter: "@todonoticias"
    hashtag: "#TN"
    feed_noticias: "https://tn.com.ar/googlenews.xml"
    categorias:
      - "deportes"
      - "policiales"
      - "sociedad"
      - "tecno"
      - "espectaculos"
      - "salud"
      - "economia"
      - "internacional"
      - "musica"
      - "autos"
      - "politica"
      - "estilo"
      - "opinion"

  - tag: "popular"
    descripcion: "Diario Popular"
    twitter: "@populardiario"
    hashtag: "#DiarioPopular"
    feed_noticias: "https://www.diariopopular.com.ar/sitemap.xml"
    categorias:
      - "general"
      - "politica"
      - "economia"
      - "internacionales"
      - "policiales"
      - "deportes"
      - "espectaculos"
      - "tecnologia"
      - "salud"
      - "horoscopo"

  - tag: "casarosada"
    descripcion: "Casa Rosada (2015-2019)"
    twitter: "@CasaRosada"
    hashtag: "#CasaRosada"
    feed_noticias: "https://www.casarosada.gob.ar/informacion/discursos/37-informacion?format=feed"
    feed_historico: "https://www.casarosada.gob.ar/informacion/archivo?format=feed"
    feeds:
      - tag: "todo"
        url: "https://www.casarosada.gob.ar/informacion/discursos/37-informacion?format=feed"