diarios:
  - tag: "lanacion"
    twitter: "@LANACION"
    feed_noticias: "https://www.lanacion.com.ar/ln-news.xml"
    feeds:
      - tag: "politica"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30"
      - tag: "economia"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272"
      - tag: "sociedad"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773"
      - tag: "internacional"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7"
      - tag: "deportes"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131"
      - tag: "espectaculos"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120"


  - tag: "clarin"
    twitter: "@clarincom"
    feed_noticias: "https://www.clarin.com/sitemap_google_news.xml"
    feeds:
      - tag: "politica"
        url: "https://www.clarin.com/rss/politica/"
      - tag: "economia"
        url: "https://www.clarin.com/rss/economia/"
      - tag: "sociedad"
        url: "https://www.clarin.com/rss/sociedad/"
      - tag: "internacional"
        url: "https://www.clarin.com/rss/mundo/"
      - tag: "deportes"
        url: "https://www.clarin.com/rss/deportes/"
      - tag: "espectaculos"
        url: "https://www.clarin.com/rss/espectaculos/"
      - tag: "cultura"
        url: "https://www.clarin.com/rss/cultura/"

  - tag: "infobae"
    twitter: "@infobae"
    feeds:
      - tag: "politica"
        url: "https://www.infobae.com/feeds/rss/sites/politica/"
      - tag: "economia"
        url: "https://www.infobae.com/feeds/rss/sites/economia/"
      - tag: "sociedad"
        url: "https://www.infobae.com/feeds/rss/sites/sociedad/"
      - tag: "internacional"
        url: "https://www.infobae.com/feeds/rss/sites/mundo/"
      - tag: "deportes"
        url: "https://www.infobae.com/feeds/rss/sites/mundo/"
      - tag: "espectaculos"
        url: "https://www.infobae.com/feeds/rss/sites/teleshow/"
      - tag: "cultura"
        url: "https://www.infobae.com/feeds/rss/sites/cultura/"

  - tag: "paginadoce"
    twitter: "@pagina12"
    feed_noticias: "https://www.pagina12.com.ar/breakingnews.xml"
    feeds:
      - tag: "politica"
        url: "https://www.pagina12.com.ar/rss/secciones/el-pais/notas"
      - tag: "economia"
        url: "https://www.pagina12.com.ar/rss/secciones/economia/notas"
      - tag: "sociedad"
        url: "https://www.pagina12.com.ar/rss/secciones/sociedad/notas"
      - tag: "internacional"
        url: "https://www.pagina12.com.ar/rss/secciones/el-mundo/notas"
      - tag: "deportes"
        url: "https://www.pagina12.com.ar/rss/secciones/deportes/notas"
      - tag: "espectaculos"
        url: "https://www.pagina12.com.ar/rss/suplementos/cultura-y-espectaculos/notas"
      - tag: "cultura"
        url: "https://www.pagina12.com.ar/rss/secciones/cultura/notas"

  - tag: "eldestape"
    twitter: "@eldestapeweb"
    feed_noticias: "https://www.eldestapeweb.com/sitemap-news.xml"
    feeds:
      - tag: "todo"
        url: "https://www.eldestapeweb.com/sitemap-news.xml"

  - tag: "casarosada"
    twitter: "@CasaRosada"
    feed_noticias: "https://www.casarosada.gob.ar/informacion/discursos?format=feed"
    feeds:
      - tag: "todo"
        url: "https://www.casarosada.gob.ar/informacion/discursos?format=feed"