diarios:
  - tag: "lanacion"
    descripcion: "La Nacion"
    twitter: "@LANACION"
    feed_noticias: "https://www.lanacion.com.ar/ln-news.xml"
    feeds:
      - tag: "politica"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30"
      - tag: "economia"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272"
      - tag: "sociedad"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773"
      - tag: "internacional"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7"
      - tag: "deportes"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131"
      - tag: "espectaculos"
        url: "http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120"


  - tag: "clarin"
    descripcion: "Clarin"
    twitter: "@clarincom"
    feed_noticias: "https://www.clarin.com/sitemap_google_news.xml"
    feeds:
      - tag: "politica"
        url: "https://www.clarin.com/rss/politica/"
      - tag: "economia"
        url: "https://www.clarin.com/rss/economia/"
      - tag: "sociedad"
        url: "https://www.clarin.com/rss/sociedad/"
      - tag: "internacional"
        url: "https://www.clarin.com/rss/mundo/"
      - tag: "deportes"
        url: "https://www.clarin.com/rss/deportes/"
      - tag: "espectaculos"
        url: "https://www.clarin.com/rss/espectaculos/"
      - tag: "cultura"
        url: "https://www.clarin.com/rss/cultura/"

  - tag: "infobae"
    descripcion: "Infobae"
    twitter: "@infobae"
    feeds:
      - tag: "politica"
        url: "https://www.infobae.com/feeds/rss/sites/politica/"
      - tag: "economia"
        url: "https://www.infobae.com/feeds/rss/sites/economia/"
      - tag: "sociedad"
        url: "https://www.infobae.com/feeds/rss/sites/sociedad/"
      - tag: "internacional"
        url: "https://www.infobae.com/feeds/rss/sites/america/"
      - tag: "deportes"
        url: "https://www.infobae.com/feeds/rss/sites/deportes-2/"
      - tag: "espectaculos"
        url: "https://www.infobae.com/feeds/rss/sites/teleshow/"
      - tag: "cultura"
        url: "https://www.infobae.com/feeds/rss/sites/cultura/"

  - tag: "paginadoce"
    descripcion: "Pagina 12"
    twitter: "@pagina12"
    feed_noticias: "https://www.pagina12.com.ar/breakingnews.xml"
    feeds:
      - tag: "politica"
        url: "https://www.pagina12.com.ar/rss/secciones/el-pais/notas"
      - tag: "economia"
        url: "https://www.pagina12.com.ar/rss/secciones/economia/notas"
      - tag: "sociedad"
        url: "https://www.pagina12.com.ar/rss/secciones/sociedad/notas"
      - tag: "internacional"
        url: "https://www.pagina12.com.ar/rss/secciones/el-mundo/notas"
      - tag: "deportes"
        url: "https://www.pagina12.com.ar/rss/secciones/deportes/notas"
      - tag: "espectaculos"
        url: "https://www.pagina12.com.ar/rss/suplementos/cultura-y-espectaculos/notas"
      - tag: "cultura"
        url: "https://www.pagina12.com.ar/rss/secciones/cultura/notas"

  - tag: "eldestape"
    descripcion: "El Destape"
    twitter: "@eldestapeweb"
    feed_noticias: "https://www.eldestapeweb.com/sitemap-news.xml"

  - tag: "telam"
    descripcion: "Telam"
    twitter: "@AgenciaTelam"
    feeds:
      - tag: "politica"
        url: "https://www.telam.com.ar/rss2/politica.xml"
      - tag: "economia"
        url: "https://www.telam.com.ar/rss2/economia.xml"
      - tag: "sociedad"
        url: "https://www.telam.com.ar/rss2/sociedad.xml"
      - tag: "internacional"
        url: "https://www.telam.com.ar/rss2/internacional.xml"
      - tag: "deportes"
        url: "https://www.telam.com.ar/rss2/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.telam.com.ar/rss2/espectaculos.xml"
      - tag: "cultura"
        url: "https://www.telam.com.ar/rss2/cultura.xml"

  - tag: "perfil"
    descripcion: "Perfil"
    twitter: "@perfilcom"
    feeds:
      - tag: "politica"
        url: "https://www.perfil.com/rss/politica.xml"
      - tag: "economia"
        url: "https://www.perfil.com/rss/economia.xml"
      - tag: "sociedad"
        url: "https://www.perfil.com/rss/sociedad.xml"
      - tag: "internacional"
        url: "https://www.perfil.com/rss/internacional.xml"
      - tag: "deportes"
        url: "https://www.perfil.com/rss/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.perfil.com/rss/espectaculos.xml"
      - tag: "cultura"
        url: "https://www.perfil.com/rss/cultura.xml"

  - tag: "ambito"
    descripcion: "Ambito"
    twitter: "@Ambitocom"
    feeds:
      - tag: "politica"
        url: "https://www.ambito.com/rss/politica.xml"
      - tag: "economia"
        url: "https://www.ambito.com/rss/economia.xml"
      - tag: "sociedad"
        url: "https://www.ambito.com/rss/informacion-general.xml"
      - tag: "internacional"
        url: "https://www.ambito.com/rss/mundo.xml"
      - tag: "deportes"
        url: "https://www.ambito.com/rss/deportes.xml"
      - tag: "espectaculos"
        url: "https://www.ambito.com/rss/espectaculos.xml"

  - tag: "tn"
    descripcion: "TN"
    twitter: "@todonoticias"
    feed_noticias: "https://tn.com.ar/googlenews.xml"
    feeds:
      - tag: "politica"
        url: "http://tn.com.ar/feed/politica"
      - tag: "sociedad"
        url: "http://tn.com.ar/feed/sociedad"
      - tag: "internacional"
        url: "http://tn.com.ar/feed/internacional"
      - tag: "deportes"
        url: "http://tn.com.ar/feed/deportes"
      - tag: "espectaculos"
        url: "http://tn.com.ar/feed/show"

  - tag: "casarosada"
    descripcion: "Casa Rosada (2015-2019)"
    twitter: "@CasaRosada"
    feed_noticias: "https://www.casarosada.gob.ar/informacion/discursos?format=feed"
    feeds:
      - tag: "todo"
        url: "https://www.casarosada.gob.ar/informacion/discursos?format=feed"